apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-flask
  labels:
    app: python-flask
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-flask
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: python-flask-cont
        image: baluomkar/python-flask:latest
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
